// Wizard Types
export const GO_TO_PAGE = 'GO_TO_PAGE';
export const FETCH_WIZARD = 'FETCH_WIZARD';
export const UPDATE_WIZARD = 'UPDATE_WIZARD';
export const UPDATE_TRAVELTYPE = 'UPDATE_TRAVELTYPE';
export const UPDATE_CLIENTINFO = 'UPDATE_CLIENTINFO';
export const UPDATE_PURPOSEOFVISIT = 'UPDATE_PURPOSEOFVISIT';
export const UPDATE_FLIGHTDETAILS = 'UPDATE_FLIGHTDETAILS';
export const UPDATE_VISA = 'UPDATE_VISA';
export const UPDATE_HOTELDETAILS = 'UPDATE_HOTELDETAILS';
export const UPDATE_LOCALTRANSPORTDETAILS = 'UPDATE_LOCALTRANSPORTDETAILS';

// User Types
export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER';
export const RELOAD_LOGGED_USER = 'RELOAD_LOGGED_USER';


// Requests View Types
export const FETCH_VIEW = 'FETCH_VIEW';
export const UPDATE_VIEW = 'UPDATE_VIEW';

