export const GO_TO_PAGE = 'GO_TO_PAGE';

export const FETCH_WIZARD = 'FETCH_WIZARD';

export const UPDATE_TRAVELTYPE = 'UPDATE_TRAVELTYPE';
export const UPDATE_CLIENTINFO = 'UPDATE_CLIENTINFO';
export const UPDATE_PURPOSEOFVISIT = 'UPDATE_PURPOSEOFVISIT';
export const UPDATE_FLIGHTDETAILS = 'UPDATE_FLIGHTDETAILS';
export const UPDATE_HOTELDETAILS = 'UPDATE_HOTELDETAILS';
export const UPDATE_LOCALTRANSPORTDETAILS = 'UPDATE_LOCALTRANSPORTDETAILS';
